version: '3.9'

services:
  assignment-app:
    command: start:watch
    build:
      context: .
    ports:
      - '127.0.0.1:8080:8080'
    volumes:
      - './src:/app/src'
    environment:
      PORT: '8080'
